name: widget-server pipe ECR

on:
  push:
    branches:
      - "main"

jobs:
  Build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Configure Node
        id: configure-node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm
        id: intall-pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: Install dependecies
        id: install-dependencies
        run: |
          pnpm install

      - name: Configure AWS Credentials
        id: configure-aws-credentials
        uses: aws-actions/configure-aws-credentials@v5.1.1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Login to AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set up Docker Buildx
        id: set-up-docker-buildx
        uses: docker/setup-buildx-action@v3

      - name: Generate tag
        id: generate_tag
        run: |
          SHA=$(echo $GITHUB_SHA | head -c7)
          echo "sha=$SHA" >> $GITHUB_OUTPUT

      - name: Build and push the image to AWS ECR
        uses: docker/build-push-action@v6
        with:
          context: .
          load: true
          cache-from: type-gha
          cache-to: type=gha,mode=max
          tags: |
            ${{ steps.login-ecr.outputs.registry }}/${{ vars.ECR_REPOSITORY }}:test

      - name: Run Trivy vulnerability scanner
        id: run-trivy-scanner
        uses: aquasecurity/trivy-action@0.29.0
        with:
          image-ref: "${{ steps.login-ecr.outputs.registry }}/${{ vars.ECR_REPOSITORY }}:test"
          format: "table"
          ignore-unfixed: true
          vuln-type: "os,library"
          severity: "CRITICAL,HIGH,MEDIUM,LOW"

      - name: Build and push the image to AWS ECR
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          cache-from: type-gha
          tags: |
            ${{ steps.login-ecr.outputs.registry }}/${{ vars.ECR_REPOSITORY }}:${{steps.generate_tag.outputs.sha}}

      - name: Render Task Definition
        id: render-task-definition
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: .aws/task-definition.json
          container-name: widget-server
          image: ${{ steps.login-ecr.outputs.registry }}/${{ vars.ECR_REPOSITORY }}:${{steps.generate_tag.outputs.sha}}
      
      - name: Deploy Amazon ECS
        id: deploy-amazon-ecs
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{ steps.render-task-definition.outputs.task-definition }}
          service: widget-server
          cluster: rocketseat-ecs-widget
          wait-for-service-stability-seconds: true

      # - name: Deploy to App Runner
      #   id: deploy-to-app-runner
      #   uses: awslabs/amazon-app-runner-deploy@main
      #   with:
      #     service: ${{ vars.APP_RUNNER_SERVICE_NAME }}
      #     image: ${{ steps.login-ecr.outputs.registry }}/${{ vars.ECR_REPOSITORY }}:${{steps.generate_tag.outputs.sha}}
      #     region: ${{ vars.AWS_REGION }}
      #     access-role-arn: ${{ secrets.ROLE_ARN }}
      #     cpu: 1
      #     memory: 2
      #     port: 3333
      #     wait-for-service-stability-seconds: 60

      # - name: App Runner Check
      #   run: echo "App running... ${{ steps.deploy-to-app-runner.outputs.service-url }}"

